/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package montador;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Gerson Menezes
 */
public class Tela2 extends javax.swing.JFrame {

    public static String ArquivoCarregado = new String("") ;
    protected static DefaultListModel<String> listMemoryModel = new DefaultListModel<>();
    protected static DefaultListModel<String> symbolTableModel = new DefaultListModel<>();
    private Montador montador = new Montador();
    public static Memory memory = new Memory();
    public Emulador emulador = new Emulador();
    public Carregador carregador = new Carregador();
    public static String modulo1text = new String();
    public static String modulo2text = new String();
    public static final int DC = 3000;
    public static final int CS = 1000;
    //private Emulador emulador = new Emulador();
    /**
     * Creates new form Tela2
     */
    public Tela2() {
        initComponents();
        //updateInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sourceCodePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        codigoFonteLabel2 = new javax.swing.JLabel();
        carregarArquivoButton = new javax.swing.JButton();
        assembleButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        memoryPanel = new javax.swing.JPanel();
        memoryLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        memoryJList = new javax.swing.JList<>();
        localizarField = new javax.swing.JTextField();
        localizarLabel = new javax.swing.JLabel();
        localizaMemoryButton = new javax.swing.JButton();
        symbolTablePanel = new javax.swing.JPanel();
        symbolScroll = new javax.swing.JScrollPane();
        jListSimbolos = new javax.swing.JList<>();
        symbolTableLabel = new javax.swing.JButton();
        registersPanel = new javax.swing.JPanel();
        registersJList = new javax.swing.JScrollPane();
        registersList = new javax.swing.JList<>();
        registersLabel = new javax.swing.JLabel();
        executePanel = new javax.swing.JPanel();
        runStepButton = new javax.swing.JButton();
        runAllButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        terminalPanel = new javax.swing.JPanel();
        outputLabel = new javax.swing.JLabel();
        terminalTextField = new javax.swing.JTextField();
        enterTerminalButton = new javax.swing.JButton();
        terminalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sourceCodePanel.setBackground(new java.awt.Color(204, 255, 255));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        codigoFonteLabel2.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel2.setText("Source code");
        codigoFonteLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        carregarArquivoButton.setText("Load File");
        carregarArquivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarArquivoButtonActionPerformed(evt);
            }
        });

        assembleButton.setText("Assemble and Link");
        assembleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assembleButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load Code to Memory");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sourceCodePanelLayout = new javax.swing.GroupLayout(sourceCodePanel);
        sourceCodePanel.setLayout(sourceCodePanelLayout);
        sourceCodePanelLayout.setHorizontalGroup(
            sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourceCodePanelLayout.createSequentialGroup()
                .addGroup(sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(codigoFonteLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(sourceCodePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assembleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carregarArquivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sourceCodePanelLayout.setVerticalGroup(
            sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourceCodePanelLayout.createSequentialGroup()
                .addComponent(codigoFonteLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carregarArquivoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assembleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        memoryPanel.setBackground(new java.awt.Color(204, 204, 255));

        memoryLabel.setBackground(new java.awt.Color(0, 0, 0));
        memoryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memoryLabel.setText("Memory");
        memoryLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane4.setViewportView(memoryJList);

        localizarField.setToolTipText("test\n");
        localizarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarFieldActionPerformed(evt);
            }
        });

        localizarLabel.setText("Find Memory");

        localizaMemoryButton.setText("Enter");
        localizaMemoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizaMemoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memoryPanelLayout = new javax.swing.GroupLayout(memoryPanel);
        memoryPanel.setLayout(memoryPanelLayout);
        memoryPanelLayout.setHorizontalGroup(
            memoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(memoryPanelLayout.createSequentialGroup()
                        .addComponent(localizarField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localizaMemoryButton))
                    .addComponent(localizarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        memoryPanelLayout.setVerticalGroup(
            memoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(localizarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localizarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localizaMemoryButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        symbolTablePanel.setBackground(new java.awt.Color(255, 204, 204));

        symbolScroll.setViewportView(jListSimbolos);

        symbolTableLabel.setText("Symbol Table");

        javax.swing.GroupLayout symbolTablePanelLayout = new javax.swing.GroupLayout(symbolTablePanel);
        symbolTablePanel.setLayout(symbolTablePanelLayout);
        symbolTablePanelLayout.setHorizontalGroup(
            symbolTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symbolTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(symbolTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(symbolTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(symbolScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        symbolTablePanelLayout.setVerticalGroup(
            symbolTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, symbolTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(symbolTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(symbolScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        registersPanel.setBackground(new java.awt.Color(204, 255, 204));

        registersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        registersJList.setViewportView(registersList);

        registersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registersLabel.setText("Registers");

        javax.swing.GroupLayout registersPanelLayout = new javax.swing.GroupLayout(registersPanel);
        registersPanel.setLayout(registersPanelLayout);
        registersPanelLayout.setHorizontalGroup(
            registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registersJList)
                    .addComponent(registersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registersPanelLayout.setVerticalGroup(
            registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registersJList, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        executePanel.setBackground(new java.awt.Color(255, 255, 204));

        runStepButton.setText("Run Step");
        runStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runStepButtonActionPerformed(evt);
            }
        });

        runAllButton.setText("Run All");
        runAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runAllButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout executePanelLayout = new javax.swing.GroupLayout(executePanel);
        executePanel.setLayout(executePanelLayout);
        executePanelLayout.setHorizontalGroup(
            executePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(executePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(executePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(runStepButton, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(runAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        executePanelLayout.setVerticalGroup(
            executePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(executePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(executePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(runAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(runStepButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        terminalPanel.setBackground(new java.awt.Color(0, 102, 102));

        outputLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(255, 255, 255));
        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputLabel.setText("Output Message");

        enterTerminalButton.setText("Enter");
        enterTerminalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTerminalButtonActionPerformed(evt);
            }
        });

        terminalLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        terminalLabel.setForeground(new java.awt.Color(255, 255, 255));
        terminalLabel.setText("Terminal");

        javax.swing.GroupLayout terminalPanelLayout = new javax.swing.GroupLayout(terminalPanel);
        terminalPanel.setLayout(terminalPanelLayout);
        terminalPanelLayout.setHorizontalGroup(
            terminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(terminalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(terminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, terminalPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(terminalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(terminalPanelLayout.createSequentialGroup()
                        .addGroup(terminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(terminalPanelLayout.createSequentialGroup()
                                .addComponent(terminalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(enterTerminalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        terminalPanelLayout.setVerticalGroup(
            terminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(terminalPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(terminalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(terminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terminalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterTerminalButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sourceCodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(terminalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(memoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(executePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(symbolTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(362, 362, 362))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(registersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(symbolTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(memoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(executePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(sourceCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(terminalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(662, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarArquivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarArquivoButtonActionPerformed
       
        
        try {                                                      
            
            ProcessaMacro processador;
            processador = new ProcessaMacro("modulo1Unexpanded", "modulo1");
            processador.processa();
            processador = new ProcessaMacro("modulo2Unexpanded", "modulo2");
            processador.processa();
            
            String linha = new String();
            String CaminhoDoArquivo = new String(System.getProperty("user.dir")+"/src/main/java/arquivos_txt/modulo1.txt");
            String CaminhoDoArquivo2 = new String(System.getProperty("user.dir")+"/src/main/java/arquivos_txt/modulo2.txt");
            BufferedReader buffRead; //reader do arquivo
            BufferedReader buffRead2; //reader do arquivo
            
            try {
                buffRead = new BufferedReader(new FileReader(CaminhoDoArquivo));
                buffRead2 = new BufferedReader(new FileReader(CaminhoDoArquivo2));
                
                linha = buffRead.readLine();
                while (linha!=null) {
                    ArquivoCarregado = ArquivoCarregado.concat(linha+"\n");
                    linha= buffRead.readLine();
                }
                linha = buffRead2.readLine();
                while (linha!=null) {
                    ArquivoCarregado = ArquivoCarregado.concat(linha+"\n");
                    linha= buffRead2.readLine();
                }
                jTextArea.setText(ArquivoCarregado);
                
                buffRead.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Tela2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Tela2.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(Tela2.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_carregarArquivoButtonActionPerformed

    private void assembleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assembleButtonActionPerformed
        try{                                                                               // Carrega código fonte e transforma em intermediario
            montador.primeira_passagem();
            jListSimbolos.setModel(symbolTableModel);
        } catch(IOException e){ 
            System.out.println("Erro 404: " + e.getMessage());
        }
        
        String linha = new String();
        String modulo1Text = new String(System.getProperty("user.dir")+"/src/main/java/arquivos_txt/firstPass.txt");
        //String modulo2Text = new String(System.getProperty("user.dir")+"/src/main/java/arquivos_txt/modulo2.txt");
        BufferedReader buffRead1; //reader do arquivo
        //BufferedReader buffRead2; //reader do arquivo
        ArquivoCarregado = ""; // reseta
        
        try {
            buffRead1 = new BufferedReader(new FileReader(modulo1Text));
           // buffRead2 = new BufferedReader(new FileReader(modulo2Text));
                  
            linha = buffRead1.readLine();
            while (linha!=null) {                
                ArquivoCarregado = ArquivoCarregado.concat(linha+"\n");
                linha = buffRead1.readLine();
            }
            buffRead1.close();
            
           /* linha = buffRead2.readLine();
            while (linha!=null) {                
                ArquivoCarregado = ArquivoCarregado.concat(linha+"\n");
                linha = buffRead2.readLine();
            }
            buffRead2.close();*/
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Tela2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Tela2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            montador.segunda_passagem();
        } catch(IOException e){ 
            System.out.println("Erro 404: " + e.getMessage());
        } 
    }//GEN-LAST:event_assembleButtonActionPerformed

    private void localizarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarFieldActionPerformed
        String str = localizarField.getText();
        int adress = Integer.parseInt(str);
        if(adress<8192 || adress>0){
            memoryJList.ensureIndexIsVisible(adress+15);
        }
        
    }//GEN-LAST:event_localizarFieldActionPerformed


    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        carregador.loadCodigo_Obj();
        this.updateInterface();
        memoryJList.ensureIndexIsVisible(CS+15);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void runStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runStepButtonActionPerformed
        emulador.step();
        this.updateInterface();
        memoryJList.ensureIndexIsVisible(CS + emulador.IP + 15);
    }//GEN-LAST:event_runStepButtonActionPerformed

    private void runAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runAllButtonActionPerformed
        emulador.run();
        this.updateInterface();
    }//GEN-LAST:event_runAllButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        emulador.reset();
        this.updateInterface();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void enterTerminalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTerminalButtonActionPerformed
        emulador.input(terminalTextField.getText());
        updateInterface();
    }//GEN-LAST:event_enterTerminalButtonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        memoryJList.ensureIndexIsVisible(Integer.parseInt(localizarField.getText()) + 15);
        localizarField.setText("");

    }//GEN-LAST:event_jButton1MouseClicked

    private void terminalTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terminalTextFieldKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_terminalTextFieldKeyTyped

    private void localizaMemoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizaMemoryButtonActionPerformed
        String str = localizarField.getText();
        int adress = Integer.parseInt(str);
        if(adress<8192 || adress>0){
            memoryJList.ensureIndexIsVisible(adress+15);
        }
    }//GEN-LAST:event_localizaMemoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela2().setVisible(true);
            }
        });
    }

    private void updateInterface(){
        listMemoryModel = new DefaultListModel<>();
        for(int i = 0;i<8192;i++){
            listMemoryModel.addElement(String.format("%04d", i)+" - "+String.format("0x%02X", memory.getPalavra(i)));
        }
        memoryJList.setModel(listMemoryModel);

        DefaultListModel<String> listRegisterModel = new DefaultListModel<>();
        listRegisterModel.addElement("AX: "+ String.format("0x%04X",emulador.AX));
        listRegisterModel.addElement("DX: "+ String.format("0x%04X",emulador.DX));
        listRegisterModel.addElement("SP: "+ String.format("0x%04X",emulador.SP));
        listRegisterModel.addElement("SI: "+ String.format("0x%01X",emulador.SI));
        listRegisterModel.addElement("IP: "+ String.format("0x%04X",emulador.IP));
        listRegisterModel.addElement("SR: "+ String.format("0x%04X",emulador.SR));
        listRegisterModel.addElement("DS: "+ String.format("0x%04X",emulador.DS));
        listRegisterModel.addElement("CS: "+ String.format("0x%04X",emulador.CS));
        listRegisterModel.addElement("SS: "+ String.format("0x%04X",emulador.SS));
        registersList.setModel(listRegisterModel);
        
        outputLabel.setText(emulador.outputStream!=null ? emulador.outputStream : "Output Message...");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assembleButton;
    private javax.swing.JButton carregarArquivoButton;
    private javax.swing.JLabel codigoFonteLabel2;
    private javax.swing.JButton enterTerminalButton;
    private javax.swing.JPanel executePanel;
    private javax.swing.JList<String> jListSimbolos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton localizaMemoryButton;
    private javax.swing.JTextField localizarField;
    private javax.swing.JLabel localizarLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JList<String> memoryJList;
    private javax.swing.JLabel memoryLabel;
    private javax.swing.JPanel memoryPanel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JScrollPane registersJList;
    private javax.swing.JLabel registersLabel;
    private javax.swing.JList<String> registersList;
    private javax.swing.JPanel registersPanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton runAllButton;
    private javax.swing.JButton runStepButton;
    private javax.swing.JPanel sourceCodePanel;
    private javax.swing.JScrollPane symbolScroll;
    private javax.swing.JButton symbolTableLabel;
    private javax.swing.JPanel symbolTablePanel;
    private javax.swing.JLabel terminalLabel;
    private javax.swing.JPanel terminalPanel;
    private javax.swing.JTextField terminalTextField;
    // End of variables declaration//GEN-END:variables
}
