/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int NEWVAR = 7;
  /** RegularExpression Id. */
  int FUNC = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int BOOLEAN = 10;
  /** RegularExpression Id. */
  int ACHAVES = 11;
  /** RegularExpression Id. */
  int FCHAVES = 12;
  /** RegularExpression Id. */
  int APARENTESES = 13;
  /** RegularExpression Id. */
  int FPARENTESES = 14;
  /** RegularExpression Id. */
  int ACOLCHETES = 15;
  /** RegularExpression Id. */
  int FCOLCHETES = 16;
  /** RegularExpression Id. */
  int SEMICOLON = 17;
  /** RegularExpression Id. */
  int CIF = 18;
  /** RegularExpression Id. */
  int CTHEN = 19;
  /** RegularExpression Id. */
  int CWHILE = 20;
  /** RegularExpression Id. */
  int CREPEAT = 21;
  /** RegularExpression Id. */
  int CUNTIL = 22;
  /** RegularExpression Id. */
  int CRETURN = 23;
  /** RegularExpression Id. */
  int CATRIB = 24;
  /** RegularExpression Id. */
  int CSOUT = 25;
  /** RegularExpression Id. */
  int CSRINT = 26;
  /** RegularExpression Id. */
  int OPADD = 27;
  /** RegularExpression Id. */
  int OPSUB = 28;
  /** RegularExpression Id. */
  int OPMULT = 29;
  /** RegularExpression Id. */
  int OPDIV = 30;
  /** RegularExpression Id. */
  int OPAND = 31;
  /** RegularExpression Id. */
  int OPOR = 32;
  /** RegularExpression Id. */
  int OPLESSTHAN = 33;
  /** RegularExpression Id. */
  int OPGREATERTHAN = 34;
  /** RegularExpression Id. */
  int OPEQUAL = 35;
  /** RegularExpression Id. */
  int OPNOT = 36;
  /** RegularExpression Id. */
  int TRUE = 37;
  /** RegularExpression Id. */
  int FALSE = 38;
  /** RegularExpression Id. */
  int STRING = 39;
  /** RegularExpression Id. */
  int NUM = 40;
  /** RegularExpression Id. */
  int ID = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"void\"",
    "\"newVar\"",
    "\"func\"",
    "\"integer\"",
    "\"bool\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"until\"",
    "\"return\"",
    "\"=\"",
    "\"System.output\"",
    "\"System.readint\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!\"",
    "\"true\"",
    "\"false\"",
    "<STRING>",
    "<NUM>",
    "<ID>",
  };

}
