/* Generated By:JavaCC: Do not edit this line. Karloff.java */
import java.io.*;
public class Karloff implements KarloffConstants {

  public static void main(String args[]) throws ParseException,IOException {

 Karloff analisador = new Karloff(new FileInputStream(args[0]));
 analisador.Karloff();
  }

  static final public void Karloff() throws ParseException {
 Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAIN:
      case VOID:
      case NEWVAR:
      case WFUNC:
      case ACHAVES:
      case FCHAVES:
      case APARENTESES:
      case FPARENTESES:
      case ACOLCHETES:
      case FCOLCHETES:
      case SEMICOLON:
      case TINT:
      case TBOOL:
      case CIF:
      case CTHEN:
      case CWHILE:
      case CREPEAT:
      case CUNTIL:
      case CRETURN:
      case CATRIB:
      case CSOUT:
      case CSRINT:
      case OPADD:
      case OPSUB:
      case OPMULT:
      case OPDIV:
      case OPAND:
      case OPOR:
      case OPLESSTHAN:
      case OPGREATERTHAN:
      case OPEQUAL:
      case NUM:
      case ID:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAIN:
        jj_consume_token(MAIN);
           System.out.println("Palavra reservada: main");
        break;
      case VOID:
        jj_consume_token(VOID);
           System.out.println("Palavra reservada: void");
        break;
      case NEWVAR:
        jj_consume_token(NEWVAR);
             System.out.println("Palavra reservada: newVar");
        break;
      case WFUNC:
        jj_consume_token(WFUNC);
            System.out.println("Palavra reservada: func");
        break;
      case ACHAVES:
        jj_consume_token(ACHAVES);
              System.out.println("Abre chaves: {");
        break;
      case FCHAVES:
        jj_consume_token(FCHAVES);
              System.out.println("Fecha chaves: }");
        break;
      case ACOLCHETES:
        jj_consume_token(ACOLCHETES);
                 System.out.println("Abre colchetes: [");
        break;
      case FCOLCHETES:
        jj_consume_token(FCOLCHETES);
                 System.out.println("Abre colchetes: ]");
        break;
      case APARENTESES:
        jj_consume_token(APARENTESES);
                  System.out.println("Abre parenteses: (");
        break;
      case FPARENTESES:
        jj_consume_token(FPARENTESES);
                  System.out.println("Fecha parenteses: )");
        break;
      case SEMICOLON:
        jj_consume_token(SEMICOLON);
                System.out.println("Ponto e v\u00edrgula: ;");
        break;
      case TINT:
        jj_consume_token(TINT);
           System.out.println("Tipo: integer");
        break;
      case TBOOL:
        jj_consume_token(TBOOL);
            System.out.println("Tipo: bool");
        break;
      case CIF:
        jj_consume_token(CIF);
          System.out.println("Comando: if");
        break;
      case CTHEN:
        jj_consume_token(CTHEN);
            System.out.println("Comando: then");
        break;
      case CWHILE:
        jj_consume_token(CWHILE);
             System.out.println("Comando: while");
        break;
      case CREPEAT:
        jj_consume_token(CREPEAT);
              System.out.println("Comando: repeat");
        break;
      case CUNTIL:
        jj_consume_token(CUNTIL);
             System.out.println("Comando: until");
        break;
      case CRETURN:
        jj_consume_token(CRETURN);
              System.out.println("Comando: return");
        break;
      case CATRIB:
        jj_consume_token(CATRIB);
             System.out.println("Comando de atribui\u00e7\u00e3o: =");
        break;
      case CSOUT:
        jj_consume_token(CSOUT);
            System.out.println("Comando: System.output");
        break;
      case CSRINT:
        jj_consume_token(CSRINT);
             System.out.println("Comando: System.readint");
        break;
      case OPADD:
        jj_consume_token(OPADD);
            System.out.println("Opera\u00e7\u00e3o: +");
        break;
      case OPSUB:
        jj_consume_token(OPSUB);
            System.out.println("Opera\u00e7\u00e3o: -");
        break;
      case OPMULT:
        jj_consume_token(OPMULT);
             System.out.println("Opera\u00e7\u00e3o: *");
        break;
      case OPDIV:
        jj_consume_token(OPDIV);
            System.out.println("Opera\u00e7\u00e3o: /");
        break;
      case OPAND:
        jj_consume_token(OPAND);
            System.out.println("Opera\u00e7\u00e3o: &");
        break;
      case OPOR:
        jj_consume_token(OPOR);
           System.out.println("Opera\u00e7\u00e3o: |");
        break;
      case OPLESSTHAN:
        jj_consume_token(OPLESSTHAN);
                 System.out.println("Opera\u00e7\u00e3o: <");
        break;
      case OPGREATERTHAN:
        jj_consume_token(OPGREATERTHAN);
                    System.out.println("Opera\u00e7\u00e3o: >");
        break;
      case OPEQUAL:
        jj_consume_token(OPEQUAL);
              System.out.println("Opera\u00e7\u00e3o: ==");
        break;
      case NUM:
        t = jj_consume_token(NUM);
            System.out.println("N\u00famero: "+ t.image);
        break;
      case ID:
        t = jj_consume_token(ID);
           System.out.println("Identificador: "+ t.image);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public KarloffTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffffffe0,0xffffffe0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x3f,0x3f,};
   }

  /** Constructor with InputStream. */
  public Karloff(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Karloff(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new KarloffTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Karloff(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new KarloffTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Karloff(KarloffTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(KarloffTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[39];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 2; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 39; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
