/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int VARDECL = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int TIPO = 11;
  /** RegularExpression Id. */
  int ATTR = 12;
  /** RegularExpression Id. */
  int OPENPAR = 13;
  /** RegularExpression Id. */
  int CLOSEPAR = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int UNTIL = 19;
  /** RegularExpression Id. */
  int THEN = 20;
  /** RegularExpression Id. */
  int REPEAT = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int SYSOUTPUT = 23;
  /** RegularExpression Id. */
  int SYSREADINT = 24;
  /** RegularExpression Id. */
  int FUNC = 25;
  /** RegularExpression Id. */
  int TOKEN_ID = 26;
  /** RegularExpression Id. */
  int TOKEN_NUM_LITERAL = 27;
  /** RegularExpression Id. */
  int OP = 28;
  /** RegularExpression Id. */
  int ID = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"newVar\"",
    "\";\"",
    "<TIPO>",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"until\"",
    "\"then\"",
    "\"repeat\"",
    "\"return\"",
    "\"System.output\"",
    "\"System.readint\"",
    "\"func\"",
    "<TOKEN_ID>",
    "<TOKEN_NUM_LITERAL>",
    "<OP>",
    "<ID>",
  };

}
